---
- name: Install Logstash
  become: true
  apt:
    name: logstash
    state: present
  notify: Start Logstash
  when: ansible_distribution == "Ubuntu"

- name: Configure Logstash
  become: true
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify: Restart Logstash
  when: ansible_distribution == "Ubuntu"

- name: Enable and Start Logstash Service
  become: true
  systemd:
    name: logstash
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"
