- name: Install Kibana
  become: true
  yum:
    name: kibana
    state: present
  notify: Start Kibana
  when: ansible_distribution == "CentOS"

- name: Configure Kibana
  become: true
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: Restart Kibana
  when: ansible_distribution == "CentOS"

- name: Enable and Start Kibana Service
  become: true
  systemd:
    name: kibana
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"
