---
- name: Install OpenJDK 11 on CentOS
  yum:
    name: java-11-openjdk-devel
    state: present
  when: ansible_distribution == "CentOS"
  become: yes


- name: Install OpenJDK 11 on Ubuntu
  apt:
    name: openjdk-11-jre-headless
    state: present
  when: ansible_distribution == "Ubuntu"
  become: yes

